"""fix evidence schema

Revision ID: 92c0d8de47f9
Revises: a50a3eeafc61
Create Date: 2026-07-24 04:45:24.305262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92c0d8de47f9'
down_revision: Union[str, Sequence[str], None] = 'a50a3eeafc61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.drop_column('notes')
        batch_op.drop_column('filename')

    # ### end Alembic commands ###
